name: flutter_banergy
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.5
  flutter_tesseract_ocr: ^0.4.24
  path_provider: ^2.1.1
  qr_bar_code_scanner_dialog: ^0.0.5
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.1.1
  animated_switcher_plus: ^1.1.0
  beamer: ^0.14.1
  permission_handler: ^11.1.0
  camera: ^0.10.5+9
  image_gallery_saver: ^2.0.3
  http: ^1.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.8.3
  crypto: ^3.0.3
  #비밀번호 검사
  #flutter_pw_validator: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/
    - assets/tessdata/
    - images/
  uses-material-design: true
